[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.associations.schema"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["associations", "schema", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.associations.schema"

[build-options]
observabilityIncluded = true
